Closes-Bug:#1634694 Fixed the issue flowseries chart in qe page are plotting because of default parser line chart, removed the default parser and moved it to the common viewconfig object monitor infra constants file. UT Results Controller: PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 537 of 537 SUCCESS (5 mins 7.048 secs / 4 mins 48.896 secs)
Storage:
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: chUtils
  at /Users/vishnuvv/workspace/24May/contrail-web-storage/webroot/dist/monitor/storage/ui/js/views/ClusterUsageView.js:9
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 90 of 90 ERROR (38.607 secs / 30.44 secs)
Storage test cases are failing even without my changes.

Server Manager:
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 129 of 129 (13 FAILED) (43.417 secs / 42.492 secs)
Server Manager test cases are failing even without my changes.

Change-Id: I3c3b9fa5c91488bc7b147ac5d7d03fb0074df066