Added updateRouter callback when orchestrationMode is none
When the orchestrationMode is 'none' and when we try to delete a logical router
with external gateway attached the delete call was failing with error.

[TypeError: Failed to parse JSON body: Object # has no method 'updateRouter']

TypeError: Failed to parse JSON body: Object #<Object> has no method 'updateRouter'
    at Object.updateRouter (/Users/mnaik/Proj/code/githubManoj/contrail-web-core/src/serverroot/common/networkmanager.api.js:76:40)
    at deleteLogicalRouterCb (/Users/mnaik/Proj/code/githubManoj/contrail-web-controller/webroot/config/networking/logicalrouter/api/logicalrouterconfig.api.js:662:28)

Added the callback to handle this issue.

Change-Id: I1dec5b55057f0cb490eab2fbe72d22f9a431d733
Related-Bug: #1764887