Related-Bug:#1633013 Fixed the issue axis values in charts are displaying with more precision like 1.000005 when we use numberFormatter function. and added the x axis value for failure cases in common chart parser.
Test cases are failing because of some other commit
WARN [web-server]: 404: /base/contrail-web-core/webroot/reports/udd/config/default.config.json
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  Error: /base/contrail-web-core/webroot/reports/udd/config/default.config.json HTTP status: 404
  at /Users/vishnuvv/workspace/24May/contrail-web-core/node_modules/requirejs/require.js:140

Change-Id: Ifab3a5984cd3ca739e3ade8ebd31cd17d0ed3810